### ISSUE TITLE
Agregar parametro `date_end` a las spiders.

### ISSUE THREAD

**Issue by matiskay** [aniversarioperu/manolo_scraper#30]
Con el fin de comenzar a testear las spider https://github.com/aniversarioperu/manolo_scraper/issues/24 y para verificar que los datos corresponden a una fecha especifica sugiero agregar una variable extra llamada `date_end`.

``` bash
scrapy crawl minedu -a date_start="2015-08-14" -a date_end="2015-08-16"
```

Esta variable va permitir crawlear paginas espeficas y ademas va permitir testar las spider puesto que los datos de una determinada fecha son invariantes.

**Comment by aniversarioperu** [comment]
buena idea

**Comment by matiskay** [comment]
El problema de tener parametros requeridos es que al momento de hacer testing de las spidera estos parametros van a ser requeridos. Sugiero que las spiders tengan una fecha de inicio y fin definida como la fecha donde se corre la spider y los parametros `date_start` y `date_end` sean opcionales.

**Comment by matiskay** [comment]
@aniversarioperu, para mi es mas natural usar dia-mes-año que usar año-mes-dia.

**Comment by matiskay** [comment]
Ademas de agregar el parametro `end_date` hay que agregar una condicional para no permitir que `start_date > end_date`.

**Comment by aniversarioperu** [comment]
creo que no sería bueno hacer hardcoding de las fechas. Tener los parámetros date_start y date_end nos dará bastante flexibilidad.

me parece haber visto una manera de usar los parametros en los tests de las spiders, pero no encuentro donde.

pero la fecha YYYY-MM-DD es del mismo formato del Python date object y es el estilo ISO.

**Comment by matiskay** [comment]
@aniversarioperu, bacan, hay que normalizar todo a `YYYY-MM-DD`.

**Comment by aniversarioperu** [comment]
el `end_date` puede ser opcional

**Comment by matiskay** [comment]
All the spiders now have the `date_end` parameter. It's time to close this issue and tackle https://github.com/aniversarioperu/manolo_scraper/issues/49.
