### ISSUE TITLE
Normalizar todos los nombres a Mayusculas

### ISSUE THREAD

**Issue by matiskay** [aniversarioperu/manolo_scraper#34]
Hay muchos nombres que estan en minusculas por ejemplo
![manolo buscador de visitas a instituciones del estado 2015-08-19 00-13-38](https://cloud.githubusercontent.com/assets/203321/9347990/2cddbf34-4607-11e5-99a3-f33a592bbea6.png)

para tener una mejor consistencia en los datos sugiero pasar todos los nombres a Mayusculas. Esto se puede hacer facilmente usando una funcion en el Item Loader.

**Comment by aniversarioperu** [comment]
pero mejor se hace en django-manolo. Si lo hacemos aquí se alterará el hash sha1

**Comment by matiskay** [comment]
@aniversarioperu, esta bien, pero debemos considerar eso para un futuro y tener los datos de las spiders limpios y normalizados.
