### ISSUE TITLE
delete and rescrape Congreso from 2015-08-13

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/manolo_scraper#37]
- [x] rescrape Congreso
- [x] rescrape Minem

due to `date` being object and not string in format YYYY-MM-DD. So the hash has changed. Need to fix the date and delete, rescrape and reindex.

See #19

**Comment by matiskay** [comment]
@aniversarioperu, I think `date` must not be an object because I got some problems when I was testing the spider. There was some complain about it from part of the item loader in the tests files. I think date must be always a string `YYYY-MM-DD` because it's data (text).

That's the reason why the hash is changing.

**Comment by aniversarioperu** [comment]
I agree, let's keep it as string `YYYY-MM-DD`.

**Comment by matiskay** [comment]
``` python
import hashlib
import datetime
from datetime import date

today = date.today()
today_str = today.strftime('%Y-%m-%d')

sha = hashlib.sha1()
sha.update(str(today))
print sha.hexdigest()

sha_str = hashlib.sha1()
sha_str.update(today_str)
print sha_str.hexdigest()
```

``` bash
python sha.py
6d3621b2ff788fbdfa4db39baeb03b167c19ed44
6d3621b2ff788fbdfa4db39baeb03b167c19ed44
```

**Comment by matiskay** [comment]
@aniversarioperu, the problem is not in the date. The problem is in the `start_date`. As far as I remember the start_date was `07:23`, with the space at the end, and the item loader removes the spaces before making the hash. In the past, the removing of the past was done in the `CleanItemPipeline`, we still do that.

**Comment by matiskay** [comment]
Here is an example:

``` python
import hashlib
import datetime
from datetime import date

with_space = hashlib.sha1()
with_space.update('07:23 ')
print with_space.hexdigest()

without_space= hashlib.sha1()
without_space.update('07:23')
print without_space.hexdigest()
```

``` bash
python sha-space.py
b76ce44d09fb156af785c8257a80c26d27a6a0f5
629d32be5184f52086cc95f9faeb9cf3f816d11e
```

**Comment by matiskay** [comment]
@aniversarioperu, Anyways, let me take a look it today. I will test that in my machine. BTW, great work.

**Comment by aniversarioperu** [comment]
I think the problem might be somewhere else. This is the original scrapped item:

``` python
{'date': '2015-08-11',
 'entity': u'SCOTIANK BANCK',
 'full_name': u'DOMINGUEZ OCA\xd1A, SANDRA BEATRIZ',
 'host_name': u'AGUADO ALFARO, JOSE ALBERTO',
 'id_document': u'DNI/LE',
 'id_number': u'10153798',
 'institution': 'congreso',
 'location': '',
 'meeting_place': '',
 'office': u'ADMINISTRACION LUIS ALBERTO SANCHEZ - FERNANDO BELAUNDE TERRY',
 'reason': u'MANTENIMIENTO PROGRAMADO',
 'sha1': 'b0faa6730cd7aedf68abe42b403f804ea720ba2d',
 'time_end': u'15:06',
 'time_start': u'09:04',
 'title': u'ADMINISTRADOR DE EDIFICIOS'}
```

note that the sha1 cannot be recreated with our current code.

**Comment by matiskay** [comment]
@aniversarioperu https://github.com/aniversarioperu/manolo_scraper/issues/19#issuecomment-132645094

**Comment by matiskay** [comment]
@aniversarioperu, can you provide me the commit sha so I can take a look? Also the date and the page so I can find the record and compare.

**Comment by aniversarioperu** [comment]
found it! https://github.com/aniversarioperu/manolo_scraper/commit/88a7f3c1eee551d015b25d0f4897687311126eaf#diff-f2eca04ef70d5d2be0f2c406534c9a17R75

it is the date was passed to the item as date object:

``` python
date_str = '11/08/2015'
item = {
    'date': datetime.datetime.strptime(date_str, '%d/%m/%Y'),
}
```

but later in the pipeline it is converted to string 2015-08-11 so that postgreSQL will not complain and save the item.

I am preparing a test for this.

**Comment by aniversarioperu** [comment]
need to rescrape all congreso

**Comment by matiskay** [comment]
@aniversarioperu, I think the string should be store in plain text not using a python object.

**Comment by aniversarioperu** [comment]
yes yes, it should.

**Comment by matiskay** [comment]
@aniversarioperu, see https://github.com/aniversarioperu/manolo_scraper/blob/master/manolo_scraper/manolo_scraper/spiders/congreso.py#L63-L64

**Comment by aniversarioperu** [comment]
that is how it should be, a string. Before it was date object.

**Comment by matiskay** [comment]
@aniversarioperu, someone made the modification https://github.com/aniversarioperu/manolo_scraper/commit/6312e8f9b6e11335234a65e8442c59c1d63c3d37 u.u

**Comment by aniversarioperu** [comment]
minem also needs rechecking?!?!

**Comment by matiskay** [comment]
@aniversarioperu, we don't have to worry to much. Basically, all the pages that we are crawling are static so we can crawl them over and over again and we can expect the same result.

**Comment by aniversarioperu** [comment]
:+1:

**Comment by matiskay** [comment]
@aniversarioperu, minem has the same problem https://github.com/aniversarioperu/manolo_scraper/blob/master/manolo_scraper/manolo_scraper/spiders/minem.py#L64-Lundefined

**Comment by matiskay** [comment]
@aniversarioperu, we should normalize everything in the near future and recreate the current database.

**Comment by matiskay** [comment]
@aniversarioperu, Take a look at "ministerio de defensa" too.

**Comment by aniversarioperu** [comment]
want to fix these? voy al sobre.

**Comment by matiskay** [comment]
@aniversarioperu, sure. I will do it now.

**Comment by aniversarioperu** [comment]
done
