### ISSUE TITLE
Create a Spider for "Minisiterio del Ambiente"

### ISSUE THREAD

**Issue by matiskay** [aniversarioperu/manolo_scraper#38]
Link: http://visitas.minam.gob.pe/frmConsulta.aspx

**Comment by matiskay** [comment]
@aniversarioperu, this particular website doesn't have a field for `document_id`. `document_id` field is required to make the hash. What is going to be the procedure for this entity? Can we set everything to DNI? Can we try to infer the document id using some rule?

**Comment by matiskay** [comment]
I will set the `document_id` to `Otros` by now.

**Comment by aniversarioperu** [comment]
done
