### ISSUE TITLE
Agregar un scraper para el Ministerio de Cultura

### ISSUE THREAD

**Issue by matiskay** [aniversarioperu/manolo_scraper#6]
He creado un scraper para obtener las visitas del ministerio de Cultura https://github.com/matiskay/mc-visits. Este scraper usa beautifulsoup para parsear los datos, la idea es reescribir este script usando scrapy para integrarlo con este repositorio.

Link: http://visitas.mcultura.gob.pe/?r=consultas/visitaConsulta/index
Datos de las visitas: https://github.com/matiskay/mc-visits/tree/master/mc-visits
Ideas para crear el scraper: https://github.com/matiskay/mc-visits/blob/master/cultura.py#L21-L42

**Comment by aniversarioperu** [comment]
chevere @matiskay 
No te animas a convertirlo a scrapy? lo podemos poner en este repo como un spider más.

**Comment by matiskay** [comment]
Listo, yo me encargo de convertir el scraper a scrapy el fin de semana.

**Comment by aniversarioperu** [comment]
:+1:

**Comment by matiskay** [comment]
Acabo de agregar la spider para el ministerio de cultura asi como para otras instituciones que comparten el mismo codigo. Todo esta en el pull request #12

**Comment by matiskay** [comment]
closed #6
