### ISSUE TITLE
Agregar un README de la lista de ministerios y entidades que faltan scrapear

### ISSUE THREAD

**Issue by matiskay** [aniversarioperu/manolo_scraper#7]
La idea es tener una lista de todos los ministerios y entidades que ya estan scrapeadas y un lista de las que faltan por scrapear.

![manolo buscador de visitas a instituciones del estado 2015-06-16 18-18-29](https://cloud.githubusercontent.com/assets/203321/8196702/1a3c2ca6-1454-11e5-8473-f61889b7ac3f.png)

**Comment by aniversarioperu** [comment]
recién estoy retomando esto. Gracias @matiskay solo tengo la lista de las entidades ya escrapeadas. puedes armarte una lista de las entidades que falta? la podemos poner en la web, o quiźa como issues?

**Comment by matiskay** [comment]
Ya, voy hacer la lista de las entidades que falta y las voy agregando a este issue. Luego podemos crear un issue para crear un spider por cada institutcion.

**Comment by aniversarioperu** [comment]
:+1:

**Comment by matiskay** [comment]
La lista de todos los organismos se encuentra en http://www.peru.gob.pe/transparencia/

## Lista de entidades
- [x] Ministerio de Transportes y Comunicaciones
  - **url**: http://scrv-reporte.mtc.gob.pe/
- [x] Ministerio de la Mujer
  - **url**: http://webapp.mimp.gob.pe:8080/visitaweb/
- [x] Ministerio de Energia y Minas
  - **url**: http://intranet.minem.gob.pe/GESTION/visitas_pcm/Busqueda/
- [x] Instituto Nacional Penitenciario
  - **url**: http://visitasadm.inpe.gob.pe/VisitasadmInpe/Controller
- [x] Ministerio de Defensa
  - **url**: http://www.mindef.gob.pe/visitas/qryvisitas.php
- [x] Presidencial del Consejo de Ministros
  - **url**: http://hera.pcm.gob.pe/Visitas/controlVisitas/index.php?r=consultas/visitaConsulta/index
- [x] Organizmo Supervisor de las Contrataciones del Estado
  - **url**: http://visitas.osce.gob.pe/controlVisitas/index.php?r=consultas/visitaConsulta/index
- [x] Ministerio de Produccion
  - **url**: http://www2.produce.gob.pe/produce/transparencia/visitas/
- [x] Tribunal Constitucional
  - **url**: http://tc.gob.pe/transparencia/visitas/
- [ ] Ministerio de Cultura
  - **url**: http://visitas.mcultura.gob.pe/?r=consultas/visitaConsulta/index
- [ ] Ministerio de Justicia
  - **url**: http://app3.minjus.gob.pe:8080/visita_web/consulta_visita_comision
- [ ] Ministerio de Relaciones Exteriores
  - **url**: http://visitas.rree.gob.pe/consultavisitas/
- [ ] Ministerio del Trabajo
  - **url**: http://www.trabajo.gob.pe/visitas.php
- [ ] Ministerio de Educacion
  - **url**: http://visitasmed.perueduca.edu.pe/controlVisitas/index.php?r=consultas/visitaConsulta
- [ ] Ministerio de Salud
  - **url**: http://intranet5.minsa.gob.pe/RegVisitasCons/listado.aspx
- [ ] Ministerio del Ambiente
  - **url**: http://visitas.minam.gob.pe/frmConsulta.aspx
- [ ] Ministerio de Agricultura y Riesgo
  - **url**: http://sistemas.minag.gob.pe/visitas/controlVisitas/index.php?r=consultas/visitaConsulta
- [ ] Ministerio de Desarrollo e Inclusion social
  - **url**: http://sdv.midis.gob.pe/sis_visita/Transparencia/Transparencia/TransparenciaVisitas
- [ ] Ministerio de Comercio Exterior y Turismo
  - **url**: http://www.mincetur.gob.pe/visitaspublico/Visitas/FrmVisitantes.aspx
- [ ] Congreso de la Republica
  - **url**: http://regvisitas.congreso.gob.pe/regvisitastransparencia/
- [ ] Presidencia
  - **url**: http://www.presidencia.gob.pe/visitas/consulta_visitas.php
- [ ] Ministerio de Vivienda
  - **url**: http://geo.vivienda.gob.pe/Visitas/controlVisitas/index.php?r=consultas/visitaConsulta/index

**Comment by aniversarioperu** [comment]
gracias @matiskay . También falta [Presidencia](http://www.presidencia.gob.pe/visitas/consulta_visitas.php) y [Ministerio de Vivienda](http://geo.vivienda.gob.pe/Visitas/controlVisitas/index.php?r=consultas/visitaConsulta/index)

**Comment by matiskay** [comment]
Genial, acabo de agregar Presidencia y Ministerio de Vivienda. Hay algunas instituciones que usan el mismo sistema para mostrar las visitas. Alli es donde se puede usar una clase base y reutilizar el codigo.  Otra cosa que note es que algunos sitios tiene captcha la solucion para esto es usar un captcha breaker o entrenar una maquina para que reconozca los digitos (una buena tarea para alguien que quiera experimentar con Machine Learning y Computer Vision).

**Comment by matiskay** [comment]
Los sistemas que usan el `Ministerio de Vivienda`, `Ministerio de Agricultura y Riesgo`, `Ministerio de Cultura`, `Organizmo Supervisor de las Contrataciones del Estado` y `Presidencial del Consejo de Ministros` son los mismos. Acabo de usar la spider de la OSCE y adaptarla para el Ministerio de Cultura. Voy a crear una Spider base para todos estos organizmos y ministerios. Mas informacion entre hoy y mañana.

**Comment by aniversarioperu** [comment]
chevere @matiskay

**Comment by matiskay** [comment]
Acabo de actualizar el README y el pull request esta en #13

**Comment by matiskay** [comment]
closed #13
