### ISSUE TITLE
minjus issues error

### ISSUE THREAD

**Issue by aniversarioperu** [aniversarioperu/manolo_scraper#71]
> 2015-09-06 16:41:51 [scrapy] ERROR: Spider error processing <POST http://app3.minjus.gob.pe:8080/visita_web/consulta_buscarVisitas> (referer: http://app3.minjus.gob.pe:8080/visita_web/consulta_paginarBusquedaVisitas)
> KeyError: 'id_number'

**Comment by matiskay** [comment]
@aniversarioperu, I will take a look at it.

**Comment by aniversarioperu** [comment]
en spider del Ministerio del Ambiente produce este error:

> 2015-09-06 18:10:14 [scrapy] ERROR: Spider error processing <POST http://visitas.minam.gob.pe/frmConsulta.aspx> (referer: http://visitas.minam.gob.pe/frmConsulta.aspx)
> KeyError: 'full_name'

**Comment by matiskay** [comment]
@aniversarioperu, todas las spiders se pusieron de acuerdo hoy para fallar. :D

**Comment by matiskay** [comment]
Curl funciona para obtener los datos pero el requests que usamos en la spider no esta mostrando los datos.

```
curl 'http://app3.minjus.gob.pe:8080/visita_web/consulta_paginarBusquedaVisitas' -H 'Content-Type: application/x-www-form-urlencoded' --data 'visita.visitanteNombres=&visita.personalNombre=&visita.oficinaNombre=&visita.sedeId=00&fechaDesde=02/09/2015&fechaHasta=02/09/2015&paginaActual=1&visita.ano=&visita.mes=&visita.fechaIngreso=&paginaNueva=0&visita.visitanteId=0&visita.personalId=0&visita.oficinaId=0'
```

``` html
<link  rel="stylesheet" href="/visita_web/css/minjus.css" type="text/css" media="screen" />
<link  rel="stylesheet" href="/visita_web/css/visita.css" type="text/css" media="screen" />

<table>
    <tr align="right">
        <td class="form_lbl">

            P�gina <select name="paginaActual" id="paginaActual" class="frm_combo" onchange="cambioPagina();">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>


</select>
  de 5

        </td>
    </tr>
</table>
```

**Comment by matiskay** [comment]
@aniversarioperu, minjus is working

``` bash
scrapy crawl justicia -a date_start="2015-09-02" -a date_end="2015-09-02"
```

**Comment by matiskay** [comment]
@aniversarioperu, ambiente is also working.

``` bash
scrapy crawl ambiente -a date_start="2015-09-02" -a date_end="2015-09-02"
```

Can you provide me the date range that you are using?

**Comment by matiskay** [comment]
@aniversarioperu, I think the problem is in `make_hash` function. I think we should use a pipeline for the hash after dropping items without any of the fields required to create the hash.

**Comment by matiskay** [comment]
``` python
from utils import makehash


# Add this pipeline after ManoloPolicyPipeline to drop items without require fields.
class ManoloMakeHash(object):
    def process_item(self, item, spider):
        return make_hash(item)
```

**Comment by matiskay** [comment]
@aniversarioperu, Is there any news?

**Comment by aniversarioperu** [comment]
testing... I am logging the scraped date so we know on which page breaks.

**Comment by aniversarioperu** [comment]
el error ocurre en la fecha 2015-01-05. con este comando:

``` shell
scrapy crawl justicia -a date_start=2015-01-05 -a date_end=2015-01-05 -t jsonlines -o ~/Desktop/justicia.json
```
