### ISSUE TITLE
Pay scrapper and parsing job, interested?

### ISSUE THREAD

**Issue by johnfelipe** [aniversarioperu/manolo_scraper#72]

**Comment by aniversarioperu** [comment]
somos pobres :crying_cat_face:

**Comment by johnfelipe** [comment]
no pero es para yo pagarte a ti por un script bien jalado en python para pasar pdf a txt y de txt a xml con un formato propio, te intersa

**Comment by aniversarioperu** [comment]
yo no tengo tiempo :disappointed: quizá @matiskay tiene tiempo?

**Comment by johnfelipe** [comment]
Email please

**Comment by matiskay** [comment]
@johnfelipe, matiskay AT gmail DOT COM
