### ISSUE TITLE
Pasar manolo a scrapinghub.

### ISSUE THREAD

**Issue by matiskay** [aniversarioperu/manolo_scraper#78]
Podemos crear una organizacion en scrapinghub y aprovechar el plan free.

![pricing scrapinghub 2016-09-26 19-12-28](https://cloud.githubusercontent.com/assets/203321/18853726/2da97796-841d-11e6-9090-b9b13a090bd7.png)

**Comment by carlosp420** [comment]
fixed in c1e909eb649f7b5b6e498502ae119c544112596e
